/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const QuizScore = IDL.Record({
  'userId' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getPageVisits' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getQuizScores' : IDL.Func([], [IDL.Vec(QuizScore)], ['query']),
  'recordPageVisit' : IDL.Func([IDL.Text], [], []),
  'submitQuizScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const QuizScore = IDL.Record({
    'userId' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'getPageVisits' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getQuizScores' : IDL.Func([], [IDL.Vec(QuizScore)], ['query']),
    'recordPageVisit' : IDL.Func([IDL.Text], [], []),
    'submitQuizScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };